todo:
# These are the available config settings.
keyword: ["@todo", "TODO"] # string|string[]
bodyKeyword: ["@body", "BODY"] # string|string[]
blobLines: 5                # number|boolean, 0 or false to disable
autoAssign: true            # string|string[]|boolean
label: true                 # boolean|string|string[]
reopenClosed: true          # boolean
